# Generated by Django 3.1.3 on 2021-03-12 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import private_storage.storage.files
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('algo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_name', models.FileField(storage=private_storage.storage.files.PrivateFileSystemStorage, upload_to='algorithms/')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_job_id', models.CharField(blank=True, max_length=16, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('algorithm_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.algorithm')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataio.dataset')),
                ('input_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='dataio.rawdata')),
                ('output_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creates', to='dataio.rawshapefile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
