kind: pipeline
type: docker
name: default
workspace:
  base: /app
steps:
- name: rebuild-dev-deps
  image: plugins/docker
  settings:
    repo: devinchristianson/birdspotter
    dockerfile: docker/Dockerfile
    context: birdspotter/
    target: dev
    tags: 
      - dev-deps
    dry_run: true 
- name: unit-test
  image: devinchristianson/birdspotter:dev-deps
  depends_on: [ rebuild-dev-deps ]
  pull: if-not-exists
  commands:
    - cd /app/birdspotter
    - python manage.py makemigrations && python manage.py migrate
    - coverage run --source='.' manage.py test
    - coverage report
    - coverage xml
- name: coverage
  image: plugins/codecov
  depends_on: [ unit-test, rebuild-dev-deps ]
  settings:
    token: 
        from_secret: codecov_token
    files:
     - /app/birdspotter/coverage.xml
- name: linter-tests
  image: devinchristianson/birdspotter:dev-deps
  depends_on: [ rebuild-dev-deps ]
  pull: if-not-exists
  commands:
    - cd /app/birdspotter
    - prospector
- name: publish-dev-image
  depends_on: [unit-test, security-tests, linter-tests]
  when:
    status: 
      - success
    event: 
      - push
  image: plugins/docker
  settings:
    repo: devinchristianson/birdspotter
    username: 
      from_secret: dockerhub_username
    password: 
      from_secret: dockerhub_password
    dockerfile: birdspotter/docker/prod.dockerfile
    context: birdspotter/
    tags: 
      - dev
    dry_run: false
trigger:
  branch:
    - master
  event:
    - push
    - pull_request
