---
kind: pipeline
type: docker
name: default
workspace:
  base: /app
steps:
- name: unit-test
  image: devinchristianson/birdspotter:dev-deps
  pull: always
  commands:
    - cd /app/birdspotter
    - python manage.py makemigrations && python manage.py migrate
    - coverage run --source='.' manage.py test
    - coverage report
    - coverage xml
- name: coverage
  image: plugins/codecov
  depends_on: [ unit-test ]
  settings:
    token: 
        from_secret: codecov_token
    files:
     - /app/birdspotter/coverage.xml
- name: linter-tests
  image: devinchristianson/birdspotter:dev-deps
  pull: always
  commands:
    - cd /app/birdspotter
    - prospector
- name: publish-dev-image
  depends_on: [unit-test, linter-tests]
  when:
    status: 
      - success
    event: 
      - push
  image: plugins/docker
  settings:
    repo: devinchristianson/birdspotter
    username: 
      from_secret: dockerhub_username
    password: 
      from_secret: dockerhub_password
    dockerfile: docker/Dockerfile
    context: birdspotter/
    target: prod
    tags: 
      - dev
- name: publish-latest-image
  depends_on: [unit-test, linter-tests]
  when:
    status: 
      - success
    event: 
      - tag
  image: plugins/docker
  settings:
    repo: devinchristianson/birdspotter
    username: 
      from_secret: dockerhub_username
    password: 
      from_secret: dockerhub_password
    dockerfile: docker/Dockerfile
    context: birdspotter/
    target: prod
    tags: 
      - latest
      - ${DRONE_TAG}
trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - tag
---
kind: signature
hmac: 244f19dd808057e7d20d50fdfb2dc7ffc5e8e14a450e211d797b978ac0c4c278

...
