---
kind: pipeline
type: docker
name: default
workspace:
  base: /app
steps:
- name: unit-test
  image: birdspotter/birdspotter:dev-deps
  commands:
    - cd /app/birdspotter
    - python manage.py makemigrations && python manage.py migrate
    - python manage.py collectstatic
    - coverage run --source='.' manage.py test
    - coverage report
    - coverage xml
- name: linter-tests
  image: birdspotter/birdspotter:dev-deps
  commands:
    - cd /app/birdspotter
    - prospector
- name: deployment-test
  image: birdspotter/birdspotter:dev
  commands:
    - cd /app/birdspotter
    - export PROD_MODE=true
    - python3 manage.py check --deploy 2>&1
- name: publish-dev-image
  depends_on: [unit-test, linter-tests, deployment-test]
  when:
    status: 
      - success
    event: 
      - push
  image: plugins/docker
  settings:
    repo: birdspotter/birdspotter
    username: 
      from_secret: dockerhub_username
    password: 
      from_secret: dockerhub_password
    dockerfile: docker/Dockerfile
    context: birdspotter/
    target: prod
    tags: 
      - dev
- name: publish-latest-image
  depends_on: [unit-test, linter-tests]
  when:
    status: 
      - success
    event: 
      - tag
  image: plugins/docker
  settings:
    repo: birdspotter/birdspotter
    username: 
      from_secret: dockerhub_username
    password: 
      from_secret: dockerhub_password
    dockerfile: docker/Dockerfile
    context: birdspotter/
    target: prod
    tags: 
      - latest
      - ${DRONE_TAG}
trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - tag
---
kind: signature
hmac: 3a5262b923b1987064405826914d7c54ed20ae48221d8f71bb55b60715bf6b3f

...
