@startuml
Class GUI{
    openWindow
    DisplayWindows()
    SwapWindow(windowName)
}
Class MapView{
    shapefile file
    DataPoint[] dataPoints
    string colorScheme

    SelectDataset()
    DisplayDataPoint()
}
Class DataView{
    string[] currentDatasets
    DataPoint[] dataPoints
    string visualization

    ChangeVisualization()
    AddDataset()
    RemoveDataSet()
    DisplayData()
}
Class BiasView{
    string currentDataset
    DataPoint[] dataPoints
    string visualization

    ChangeVisualization()
    SelectDataset()
    DisplayBias()
}
Class ImportView{
    bool canImport
    bool canExport

    Import(setName, dateRange, input/output)
    Export(setName, date, file[])

}
Class DataPoint{
    int objectID
    string IslandNamd
    string CIREG
    date PhotoDate
    string Observer
    string Species
    int Behavior
    string CertainP1
    string BehaviorP2
    string Comments
    float Point_x
    float Point_y
    float Lat
    float Long
}

GUI <|-- MapView
GUI <|-- BiasView
GUI <|-- DataView
GUI <|-- ImportView
MapView <|-- DataPoint
DataView <|-- DataPoint
BiasView <|-- DataPoint
@enduml
