@startuml
Class GUI{
    openWindow
    DisplayWindows()
    SwapWindow(windowName)
}
Class MapView{
    file: shapefile
    dataPoints: DataPoint[]
    colorScheme string

    SelectDataset()
    DisplayDataPoint()
}
Class DataView{
    currentDatasets: string[]
    dataPoints: DataPoint[]
    visualization: string

    ChangeVisualization()
    AddDataset()
    RemoveDataSet()
    DisplayData()
}
Class BiasView{
    currentDatasets: string[]
    dataPoints: DataPoint[]
    visualization: string

    ChangeVisualization()
    SelectDataset()
    DisplayBias()
}
Class ImportView{
    canImport: bool
    canExport: bool

    Import(setName, dateRange, input/output)
    Export(setName, date, file[])

}
Class DataPoint{
    objectID: int
    IslandNamd: string
    CIREG: string
    PhotoDate: date
    Observer: string
    Species: string
    Behavior: int
    CertainP1: string
    BehaviorP2: string
    Comments: string
    Point_x: float
    Point_y: float
    Lat: float
    Long: float
}

GUI <|-- MapView
GUI <|-- BiasView
GUI <|-- DataView
GUI <|-- ImportView
MapView <|-- DataPoint
DataView <|-- DataPoint
BiasView <|-- DataPoint
@enduml
