"""
Django settings for birdspotter project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import logging
from django.core.management.utils import get_random_secret_key  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! 
# Airtable task is open for this
SECRET_KEY =  os.getenv('SECRET_KEY')
if(not SECRET_KEY):
    SECRET_KEY = get_random_secret_key()
    logging.warning("WARNING - IMPORTANT: SECRET_KEY env var was not set, random secret key was used")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')
CRISPY_FAIL_SILENTLY = not DEBUG
PROD_MODE = os.getenv('PROD_MODE', 'False')

TESTING = False
TEST_RUNNER = 'birdspotter.TestRunner.TestRunner'

ALLOWED_HOSTS = []
USE_X_FORWARDED_HOST = os.getenv('USE_X_FORWARDED_HOST', 'False')
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost').split(',')
SECURE_PROXY_SSL_HEADER = ('X-Forwarded-Proto', 'https')
PROD_DB = os.getenv('PROD_DB')
PROD_FS = os.getenv('PROD_FS', 'False')
PROD_EMAIL = os.getenv('PROD_EMAIL', 'False')
if PROD_MODE and PROD_MODE.lower() == 'true': 
    PROD_DB = 'true'
    PROD_FS = 'true'
    PROD_EMAIL = 'true'
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 120
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

HEALTH_CHECK = {
    'DISK_USAGE_MAX': 90,  # percent
    'MEMORY_MIN': 100,    # in MB
}

# Application definition

INSTALLED_APPS = [
    'birdspotter.accounts',
    'birdspotter.dataio',
    'birdspotter.analysis',
    'birdspotter',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'health_check',
    'health_check.db',
    'health_check.storage',
    'crispy_forms',
    'django_mailbox',
    'private_storage'
]
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'birdspotter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, '/templates/'),
)

WSGI_APPLICATION = 'birdspotter.wsgi.application'
SILENCED_SYSTEM_CHECKS = ["security.W008"] # silence no https re-direct warning, as that is handled by the proxy 

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
if not PROD_DB or PROD_DB.lower() == 'false' :
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif PROD_DB.lower() == 'true':
    DATABASES = {    
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DBNAME'),
            'USER': os.getenv('DBUSERNAME'),
            'PASSWORD': os.getenv('DBPASSWORD'),
            'HOST': os.getenv('DBHOST'),
            'PORT': '5432',
        }   
    }
EMAIL_HOST = ''
EMAIL_PORT = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = None
EMAIL_USE_TLS = ''
EMAIL_TIMEOUT = ''
EMAIL_NOTIF_ADDR = os.getenv('EMAIL_NOTIF_ADDR', 'debug@example.org')
if not PROD_EMAIL or PROD_EMAIL.lower() == 'false' :
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
elif PROD_EMAIL.lower() == 'true' :
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'email')
    EMAIL_PORT = os.getenv('EMAIL_PORT', '25')
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
    EMAIL_TIMEOUT = 5

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'birdspotter/staticfiles')] 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Redirect to home page after login
LOGIN_REDIRECT_URL = '/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
PRIVATE_STORAGE_AUTH_FUNCTION = 'private_storage.permissions.allow_authenticated'
PRIVATE_STORAGE_ROOT = os.path.join(BASE_DIR, 'media/protected/')
PRIVATE_STORAGE_INTERNAL_URL = '/media/protected/'
if PROD_FS : 
    PRIVATE_STORAGE_ROOT = '/share/media/protected/'
    PRIVATE_STORAGE_SERVER = 'nginx'
    STATIC_URL = '/static/'
    MEDIA_URL = '/share/media/'
    MEDIA_ROOT = '/media/'
    STATIC_ROOT = '/share/static/'

SENTRY_URI = os.getenv('SENTRY_URI')
if SENTRY_URI : 
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    sentry_sdk.init(
        dsn=SENTRY_URI,
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0,

        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth) you may enable sending PII data.
        send_default_pii=True
    )