# Generated by Django 3.1.6 on 2021-04-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataio', '0002_dataset_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date_collected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
