# Generated by Django 3.1.3 on 2021-03-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataio', '0002_dataset_shared_with'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'default_permissions': (), 'permissions': [('export_dataset', 'Can export dataset')]},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='rawdata',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='rawshapefile',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='shapefile',
            options={'default_permissions': ()},
        ),
    ]
