# Generated by Django 3.1.6 on 2021-04-24 13:55

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('dataio', '0003_auto_20210401_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='path',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage, upload_to='raw_files/'),
        ),
    ]
