# Generated by Django 3.1.6 on 2021-04-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataio', '0004_auto_20210424_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
