version: "3.9"
services:
  birdspotter:
    restart: unless-stopped
    build:
      context: ../birdspotter
      dockerfile: ../docker/Dockerfile
      target: prod
    env_file: 
      - .env
    environment:
      - DBHOST=postgres
    depends_on: 
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.birdspotter.rule=Host(`birdspotter.localhost`)"
      - "traefik.http.routers.birdspotter.entrypoints=web"
    volumes:
      - media:/media
      - static:/static
  traefik:
    image: traefik:latest
    ports:
      - 8001:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - "--ping.entryPoint=ping"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.ping.address=:8082"
    depends_on: 
      - birdspotter
    healthcheck:
      test: ["CMD", "traefik" ,"healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 30
  postgres:
    restart: unless-stopped
    image: postgres:13
    env_file: 
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  static:
    image: nginx
    depends_on:
      - birdspotter
    volumes:
      - static:/usr/share/nginx/html
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.static.rule=Host(`birdspotter.localhost`) && PathPrefix(`/static`)"
    - "traefik.http.routers.static.entrypoints=web"
    - "traefik.http.routers.static.middlewares=static-stripprefix"
    - "traefik.http.middlewares.static-stripprefix.stripprefix.prefixes=/static"
  media:
    image: nginx
    depends_on:
      - birdspotter
    volumes:
      - static:/usr/share/nginx/html
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.media.rule=Host(`birdspotter.localhost`) && PathPrefix(`/static`)"
    - "traefik.http.routers.media.entrypoints=web"
    - "traefik.http.routers.media.middlewares=media-stripprefix"
    - "traefik.http.middlewares.media-stripprefix.stripprefix.prefixes=/media"
volumes:
    pgdata:
    static:
    media: 