version: "3.9"
services:
  birdspotter:
    restart: unless-stopped
    environment:
      - DBHOST=postgres
    depends_on: 
      postgres:
        condition: service_healthy
  traefik:
    image: traefik:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on: 
      - birdspotter
    healthcheck:
      test: ["CMD", "traefik" ,"healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 30
  postgres:
    restart: unless-stopped
    image: postgres:13
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    depends_on:
      - birdspotter