@startuml
start



repeat

:main_view;
if (login) then (login)
    repeat
    repeat while (valid credentials) is (no)
    ->yes;
else (no login)
endif


:select dataset;

repeat

if (get view) then (General\nUser)
    if (map_view) then (\nchange\nscreen)
        repeat
        :map_view;
        repeat while ( ) is (report\nerror)
    elseif (data_view) then (\nchange\nscreen)
        repeat
        :data_view;
        :select visualization;
        repeat while ( ) is (select\nchart)
    elseif (bias_view) then (\nchange\nscreen)
        repeat
        :bias_view;
        :select visualization;
        repeat while ( ) is (select\nchart)
    else (continue)

    endif
elseif (export) then (Registered User)
    :select save parameters;
    :select save location;

    if (confirm) then (yes)
        :save Data;
    else ()
    endif


elseif (import) then (Privileged user)
    :select data location;
    :apply dataset name;
    if (confirm) then (yes)
        :upload dataset to ACG;
    else (no)
    
    endif

endif
repeat while (return to main_view) is (no)
repeat while ( ) is ( )



@enduml
