# Generated by Django 3.1.3 on 2021-03-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouprequest',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ()},
        ),
    ]
